name: Test Staggered Schedule

on:
  # two staggered schedules
  schedule:
    - cron: '2,7,12,17,22,27,32,37,42,47,52,57 * * * *'
    - cron: '3/5 * * * *'

  # lets you fire it by hand while it’s still in a PR
  workflow_dispatch:

concurrency:
  group: every-5-min
  cancel-in-progress: true   # first copy wins, duplicates die  ↑ :contentReference[oaicite:0]{index=0}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: UTC timestamp
        run: date -u
      - name: Say hello
        run: echo "staggoooooor-test fired at $(date -u)"
